### ISSUE TITLE
CustomerSpecs, unknown type

### ISSUE THREAD

**Issue by kmcn1875** [MarcGiffing/wicket-spring-boot#127] opened 2018-01-22 11:24 UTC
Class com.giffing.wicket.spring.boot.example.repository.services.customer.specs.CustomerSpecs has a compilation error, related to the following.

`import com.giffing.wicket.spring.boot.example.model.Customer_;`
and multiple instances similar to the following...
`
return (root, query, builder) -> builder.equal(root.get(Customer_.id), id);`

Removing the unrecognised import and changing `Customer_.${attribute} `to a String `"${attribute}"` fixes the issue. 

See attached file.

[CustomerSpecs.java.txt](https://github.com/MarcGiffing/wicket-spring-boot/files/1651726/CustomerSpecs.java.txt)

**Comment by ursjoss** [comment] 2018-01-22 12:20
Is this occuring in eclipse? If so, I would assume building the project using maven outside of eclipse works fine, doesn't it?

**Comment by kmcn1875** [comment] 2018-01-22 12:28
I just checked and you're right, it builds just fine using Maven from the command line.

I found the issue in Spring STS, an Eclipse derivative, so it must be an issue in that.

**Comment by ursjoss** [comment] 2018-01-22 12:44
This can be fixed in the project setup. But the issue is only present in eclipse. I presume @MarcGiffing is working in IntelliJ ;-).

**Comment by MarcGiffing** [comment] 2018-01-22 15:50
I'm working with Eclipse STS! Thanks für the PR :)

**Comment by MarcGiffing** [comment] 2018-01-22 15:52
Note: Wicket 8 branch

**Closed** 2018-08-31 19:10 UTC
